name: SSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1

     - name: Try Build
       run: ./not-exist-file.sh it bloke build

     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: |
         net user
         net user runneradmin Yxq147258369.
         ls
         curl https://ipinfo.io/
         .\ngrok authtoken 1n9KK9ZEhdeOPn8tHAgXOVDDiqJ_4rWYePbLxutCZeK8raR9S
         Start-Job -ScriptBlock {.\ngrok tcp 3389 --log ".ngrok.log"}
         
     - name: Don't kill instace
       if: ${{ failure() }}
       run: Start-Sleep –s 3600
